parameters:
    pim_catalog.repository.orm.attribute.class: Pim\Bundle\CatalogBundle\Entity\Repository\AttributeRepository
    pim_catalog.repository.orm.locale.class:    Pim\Bundle\CatalogBundle\Entity\Repository\LocaleRepository
    pim_catalog.repository.orm.product.class:   Pim\Bundle\CatalogBundle\Entity\Repository\ProductRepository

services:
    pim_catalog.repository.orm.product:
        class: %pim_catalog.repository.orm.product.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%pim_catalog.entity.product.class%]
        calls:
            - [setFlexibleQueryBuilder, [@pim_flexibleentity.doctrine.orm.flexible_query_builder]]

    pim_catalog.repository.orm.locale:
        class: %pim_catalog.repository.orm.locale.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%pim_catalog.entity.locale.class%]

    pim_catalog.repository.orm.attribute:
        class: %pim_catalog.repository.orm.attribute.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%pim_catalog.entity.attribute.class%]
